- name: UPDATE GITHUB ISSUE
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
    - name: set datetime of local ansible control node
      set_fact:
        datetime: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}"

    - name: post issue comment
      uri:
        url: "https://api.github.com/repos/network-automation/linklight/issues/207/comments"
        method: POST
        force_basic_auth: yes
        user: "{{github_username}}"
        password: "{{github_token}}"
        validate_certs: False
        body_format: json
        body:
          body: |-
            AUTOMATED COMMENT BY ANSIBLE
            ############################
            updated at {{datetime}}

            THIS WORKFLOW HAS PASSED!

            ![well done gif animation](https://www.reactiongifs.com/r/2012/08/well_done_sir.gif)
        status_code: [200,201]
      register: test
